VirtoCommerce/vc-module-x-catalog

src/VirtoCommerce.XCatalog.Data/Index/IndexSearchRequestBuilder.cs, src/VirtoCommerce.XCatalog.Data/Queries/SearchProductQueryHandler.cs
Search localized values in `__content_{CultureName}`
https://virtocommerce.atlassian.net/browse/VCST-1540
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.XCatalog_3.802.0-pr-2-be78.zip
=> VCST-154: search by localized content field

.deployment/module/cloudDeploy.json
=> VCST-1551: Create cloudDeploy.json

VirtoCommerce.XCatalog.sln, module.keep, src/VirtoCommerce.XCatalog.Core/Schemas/FulfillmentCenterType.cs, src/VirtoCommerce.XCatalog.Data/Middlewares/EvalProductsDiscountsMiddleware.cs, src/VirtoCommerce.XCatalog.Data/Middlewares/EvalProductsInventoryMiddleware.cs, src/VirtoCommerce.XCatalog.Data/Middlewares/EvalProductsPricesMiddleware.cs, src/VirtoCommerce.XCatalog.Data/Queries/GetFulfillmentCenterQueryHandler.cs, src/VirtoCommerce.XCatalog.Data/Queries/LoadPromotionsQueryHandler.cs, src/VirtoCommerce.XCatalog.Data/Queries/SearchFulfillmentCentersQueryHandler.cs, src/VirtoCommerce.XCatalog.Web/module.manifest
https://virtocommerce.atlassian.net/browse/VCST-1543
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.XCatalog_3.803.0-pr-4-824c.zip
=> VCST-1543: add optional modules attribute

src/VirtoCommerce.XCatalog.Core/Models/SearchProductResponse.cs, src/VirtoCommerce.XCatalog.Core/Queries/ChildCategoriesQuery.cs, src/VirtoCommerce.XCatalog.Core/Queries/SearchProductQuery.cs, src/VirtoCommerce.XCatalog.Data/Mapping/ProductMappingProfile.cs, src/VirtoCommerce.XCatalog.Data/Middlewares/EvalProductsDiscountsMiddleware.cs, src/VirtoCommerce.XCatalog.Data/Middlewares/EvalProductsPricesMiddleware.cs, src/VirtoCommerce.XCatalog.Data/Queries/ChildCategoriesQueryBuilder.cs, src/VirtoCommerce.XCatalog.Data/Queries/ChildCategoriesQueryHandler.cs, src/VirtoCommerce.XCatalog.Data/Queries/SearchCategoryQueryHandler.cs, src/VirtoCommerce.XCatalog.Data/Queries/SearchProductQueryBuilder.cs, src/VirtoCommerce.XCatalog.Data/Queries/SearchProductQueryHandler.cs, src/VirtoCommerce.XCatalog.Data/Queries/SearchPropertiesQueryHandler.cs, tests/VirtoCommerce.XCatalog.Tests/Middlewares/EvalProductsTaxMiddlewareTest.cs
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.XCatalog_3.804.0-pr-6-6de3.zip
=> fix: remove old namespaces

src/VirtoCommerce.XCatalog.Core/Schemas/TierPriceType.cs
https://virtocommerce.atlassian.net/browse/VCST-1642
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.XCatalog_3.804.0-pr-8-5756.zip
=> VCST-1642: use Actual Price in TierPriceType

src/VirtoCommerce.XCatalog.Core/Models/ExpProduct.cs
https://virtocommerce.atlassian.net/browse/VCST-1626
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.XCatalog_3.806.0-pr-9-ffbf.zip
=> VCST-1626: don't resolve main FFC if in stock quantity = 0

src/VirtoCommerce.XCatalog.Core/Schemas/ProductType.cs
feat: extends product document builder with product dimensions. Weight unit, weight, measure unit, height, width, length
https://virtocommerce.atlassian.net/browse/VCST-1781
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.XCatalog_3.808.0-pr-11-2e4a.zip
=> VCST-1781: Add product dimensions

src/VirtoCommerce.XCatalog.Core/Models/ExpProduct.cs, src/VirtoCommerce.XCatalog.Core/Schemas/ProductType.cs, src/VirtoCommerce.XCatalog.Core/Schemas/VariationType.cs
feat: Extends product schema with rating. Enable review for product via external module.
https://virtocommerce.atlassian.net/browse/VCST-1853
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.XCatalog_3.810.0-pr-13-b0ae.zip
=> VCST-1853: Extend product with rating

src/VirtoCommerce.XCatalog.Core/Models/ExpProduct.cs
---
https://virtocommerce.atlassian.net/browse/VCST-1820
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.XCatalog_3.811.0-pr-14-3402.zip
=> VCST-1820: fix for tier prices discount fix

src/VirtoCommerce.XCatalog.Core/Queries/GetProductConfigurationsQuery.cs, src/VirtoCommerce.XCatalog.Core/Schemas/ProductType.cs, src/VirtoCommerce.XCatalog.Core/VirtoCommerce.XCatalog.Core.csproj, src/VirtoCommerce.XCatalog.Data/Queries/GetProductConfigurationsQueryHandler.cs, src/VirtoCommerce.XCatalog.Web/module.manifest
https://virtocommerce.atlassian.net/browse/VCST-2223
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.XCatalog_3.818.0-pr-23-97a7.zip
=> VCST-2223: update to Configurable Products

src/VirtoCommerce.XCatalog.Core/VirtoCommerce.XCatalog.Core.csproj, src/VirtoCommerce.XCatalog.Data/Extensions/ServiceCollectionExtensions.cs, src/VirtoCommerce.XCatalog.Web/Module.cs, src/VirtoCommerce.XCatalog.Web/module.manifest
playground url: /ui/playground/catalog
https://virtocommerce.atlassian.net/browse/VCST-2241
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.XCatalog_3.819.0-pr-22-e45a.zip
=> VCST-2241: add scoped schema

src/VirtoCommerce.XCatalog.Core/Extensions/RewardExtensions.cs, src/VirtoCommerce.XCatalog.Core/Models/ExpProduct.cs, src/VirtoCommerce.XCatalog.Core/VirtoCommerce.XCatalog.Core.csproj, src/VirtoCommerce.XCatalog.Web/module.manifest
https://virtocommerce.atlassian.net/browse/VCST-2305
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.XCatalog_3.820.0-pr-24-3001.zip
=> VCST-2305: Update ApplyRewards()

src/VirtoCommerce.XCatalog.Core/Extensions/OutlineExtensions.cs
feat: Add catalog as a first element of breadcrumbs
https://virtocommerce.atlassian.net/browse/VCST-2346
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.XCatalog_3.822.0-pr-25-8fcc.zip
=> VCST-2346: Add catalog as a first element of breadcrumbs

.github/workflows/module-ci.yml, src/VirtoCommerce.XCatalog.Core/VirtoCommerce.XCatalog.Core.csproj, src/VirtoCommerce.XCatalog.Data/Mapping/FacetMappingProfile.cs, src/VirtoCommerce.XCatalog.Web/module.manifest
https://virtocommerce.atlassian.net/browse/VCST-2608
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.XCatalog_3.902.0-pr-30-afa5.zip
=> VCST-2608: Fix range aggregations

src/VirtoCommerce.XCatalog.Data/Queries/ChildCategoriesQueryHandler.cs
- Use AbstractTypeFactory to create SearchProductQuery in ChildCategoriesQueryHandler like via SearchProductQueryBuilder
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.XCatalog_3.902.0-pr-28-3868.zip
=> feat: Use AbstractTypeFactory to create SearchProductQuery in ChildCategoriesQueryHandler like via SearchProductQueryBuilder

src/VirtoCommerce.XCatalog.Core/VirtoCommerce.XCatalog.Core.csproj, src/VirtoCommerce.XCatalog.Web/module.manifest
feat: Use new version of Catalog Module with typed product configuration sections
https://virtocommerce.atlassian.net/browse/VCST-2563
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.XCatalog_3.904.0-pr-31-8535.zip
=> VCST-2563 Use new version of Catalog Module

src/VirtoCommerce.XCatalog.Core/VirtoCommerce.XCatalog.Core.csproj, src/VirtoCommerce.XCatalog.Web/module.manifest
https://virtocommerce.atlassian.net/browse/VCST-2589
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.XCatalog_3.905.0-pr-33-7df5.zip
=> VCST-2589: update Xapi dependency (Mediatr)

src/VirtoCommerce.XCatalog.Data/Queries/SearchCategoryQueryHandler.cs
- GetIndexedSearchRequestBuilder
- GetStore
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.XCatalog_3.906.0-pr-39-8af1.zip
=> feat: Add virtual methods to SearchCategoryQueryHandler

src/VirtoCommerce.XCatalog.Core/Extensions/FormatExtensions.cs, src/VirtoCommerce.XCatalog.Core/Schemas/PropertyType.cs, src/VirtoCommerce.XCatalog.Core/VirtoCommerce.XCatalog.Core.csproj, src/VirtoCommerce.XCatalog.Web/module.manifest, tests/VirtoCommerce.XCatalog.Tests/Extensions/FormatExtensionsTests.cs, tests/VirtoCommerce.XCatalog.Tests/Schemas/PropertyTypeTests.cs
https://virtocommerce.atlassian.net/browse/VCST-2837
https://virtocommerce.atlassian.net/browse/VCST-2855
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.XCatalog_3.911.0-pr-42-b530.zip
=> VCST-2837: Add measure property type

src/VirtoCommerce.XCatalog.Data/Middlewares/EvalProductsTaxMiddleware.cs, tests/VirtoCommerce.XCatalog.Tests/Middlewares/EvalProductsTaxMiddlewareTest.cs, tests/VirtoCommerce.XCatalog.Tests/Schemas/ProductTypeTests.cs, tests/VirtoCommerce.XCatalog.Tests/Schemas/PropertyTypeTests.cs, tests/VirtoCommerce.XCatalog.Tests/VirtoCommerce.XCatalog.Tests.csproj
https://virtocommerce.atlassian.net/browse/VCST-2047
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.XCatalog_3.912.0-pr-45-cf66.zip
=> VCST-2047: Make VirtoCommerce.Tax optional

src/VirtoCommerce.XCatalog.Data/Index/IndexSearchRequestBuilder.cs
https://virtocommerce.atlassian.net/browse/VCST-3197
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.XCatalog_3.916.0-pr-50-88c7.zip
=> VCST-3276: modify SearchRequestBuilder

src/VirtoCommerce.XCatalog.Core/Schemas/VariationType.cs
GraphQL fields on VariationType were not "ExtendableFields" This caused type overrides to not work
=> Made Variation GraphQL fields extendable

src/VirtoCommerce.XCatalog.Core/VirtoCommerce.XCatalog.Core.csproj, src/VirtoCommerce.XCatalog.Web/module.manifest
https://virtocommerce.atlassian.net/browse/VCST-3694
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.XCatalog_3.925.0-pr-62-95f4.zip
=> VCST-3694: Update XAPI and Catalog module dependencies

Directory.Build.props, VirtoCommerce.XCatalog.sln.DotSettings, src/VirtoCommerce.XCatalog.Core/Models/ExpProductResponseGroup.cs, src/VirtoCommerce.XCatalog.Core/Models/SearchProductResponse.cs, src/VirtoCommerce.XCatalog.Core/Queries/SearchProductQuery.cs, src/VirtoCommerce.XCatalog.Core/Schemas/ProductsConnectionType.cs, src/VirtoCommerce.XCatalog.Core/Schemas/SearchProductFilterRangeValueType.cs, src/VirtoCommerce.XCatalog.Core/Schemas/SearchProductFilterResultType.cs, src/VirtoCommerce.XCatalog.Core/Schemas/SearchProductFilterValueType.cs, src/VirtoCommerce.XCatalog.Core/VirtoCommerce.XCatalog.Core.csproj, src/VirtoCommerce.XCatalog.Data/Extensions/ServiceCollectionExtensions.cs, src/VirtoCommerce.XCatalog.Data/Index/IndexSearchRequestBuilder.cs, src/VirtoCommerce.XCatalog.Data/Mapping/FacetMappingProfile.cs, src/VirtoCommerce.XCatalog.Data/Middlewares/EvalSearchRequestUserGroupsMiddleware.cs, src/VirtoCommerce.XCatalog.Data/Middlewares/ResolveSearchFiltersResponseMiddleware.cs, src/VirtoCommerce.XCatalog.Data/Queries/SearchCategoryQueryHandler.cs, src/VirtoCommerce.XCatalog.Data/Queries/SearchProductQueryBuilder.cs, src/VirtoCommerce.XCatalog.Data/Queries/SearchProductQueryHandler.cs, src/VirtoCommerce.XCatalog.Web/module.manifest
https://virtocommerce.atlassian.net/browse/VCST-3596
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.XCatalog_3.927.0-pr-59-caf0.zip
=> VCST-3596: Add range facet statistics and filters to product search result

src/VirtoCommerce.XCatalog.Core/VirtoCommerce.XCatalog.Core.csproj, src/VirtoCommerce.XCatalog.Data/Mapping/FacetMappingProfile.cs, src/VirtoCommerce.XCatalog.Data/Queries/SearchProductQueryHandler.cs, src/VirtoCommerce.XCatalog.Web/module.manifest
https://virtocommerce.atlassian.net/browse/VCST-3674
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.XCatalog_3.928.0-pr-63-1520.zip
=> VCST-3674: Order Facet results
